spring.application.name: board-game

spring:
  ### db ###
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board_game
    username: admin
    password: admin

  ### jpa ###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  ### redis ###
  data:
    redis:
      host: localhost
      port: 6379

### jwt ###
jwt:
  secret: your-secret-key-change-this-in-production-minimum-256-bits
  access-token-expiration: 1800000  # 30분 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)

### logging ###
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
